import {VERSION,createGame,avg,territory,expandable,fronts,expand,sign,pack,swap,endTurn,botTurn,standings} from './engine.js';
import {storage} from './storage.js';
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
let game=storage.load(),tab='map',selected=null,starter=null,zoom=1,busy=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=t=>`<span class="badge" style="--club:${t.color}">${t.id+1}</span>`;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
function save(){if(!storage.save(game))toast('No se pudo guardar en este navegador. Mantené esta pestaña abierta.');}
function dialog(html){modal.innerHTML=`<button class="close" data-do="close" aria-label="Cerrar">×</button>${html}`;if(!modal.open)modal.showModal();}
function header(){return `<header><a class="brand" href="./" aria-label="Trucebol inicio">TRUCEBOL<span>FÚTBOL ENTRE TRINCHERAS</span></a><div class="header-tools"><button class="version" data-do="updates">v${VERSION}</button><button class="help" data-do="help" aria-label="Cómo jugar">?</button>${game?'<button class="text-button" data-do="new">Nueva</button>':''}</div></header>`;}
function setup(){app.innerHTML=`${header()}<main class="setup"><section class="intro"><div class="eyebrow">DEMO LOCAL · SIN RELOJ</div><h1>La frontera<br>se juega<br><em>en la cancha.</em></h1><p>Pintá el barrio. Armá tu once.<br>Cuando dos banderas se cruzan,<br>se arregla con una pelota.</p><div class="hero-ball" aria-hidden="true"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="#f7edce" stroke="#234e40" stroke-width="3"/><path d="m50 30 20 14-8 24H38l-8-24Z M10 47l17-8 M28 13l9 18 M73 13l-10 19 M90 47l-18-7 M74 89l-11-20 M26 89l12-21" fill="#234e40" stroke="#234e40" stroke-width="5"/></svg><span>NO HAY APURO.<br>HAY POTRERO.</span></div></section><form id="setup" class="setup-card"><div class="eyebrow">ARMEMOS LA PARTIDA</div><h2>¿Quién se prende?</h2><label>Modo<select name="mode"><option value="solo">Yo contra equipos simulados</option><option value="local">Amigos en el mismo dispositivo</option></select></label><div class="form-row"><label>Equipos<select name="teams"><option value="2">2 equipos</option><option value="3">3 equipos</option><option value="4">4 equipos</option></select></label><label>Mapa<select name="size"><option value="8">8 × 8</option><option value="10">10 × 10</option><option value="12">12 × 12</option></select></label></div><details><summary>Reglas para experimentar</summary><p class="muted">El inicio y el momento del partido siguen a prueba. Estas opciones no fijan la regla final.</p><label>Territorio inicial<select name="startTiles"><option value="3">3 casillas por equipo</option><option value="1">1 casilla por equipo</option><option value="4">4 casillas por equipo</option></select></label><label>Frente necesario<select name="threshold"><option value="3">3 casillas de frontera</option><option value="2">2 casillas de frontera</option><option value="4">4 casillas de frontera</option></select></label><label>Al dispararse un partido<select name="timing"><option value="end">Jugar al cerrar mi turno</option><option value="immediate">Jugar enseguida y seguir mi turno</option><option value="cut">Jugar enseguida y cerrar mi turno</option></select></label></details><button class="primary start" type="submit">Al potrero <span>↗</span></button><p class="fine">3 acciones por turno · Cambios de plantel gratis<br>Guardado automático · Sin monedas en esta demo</p><button type="button" class="text-button" data-do="help">Primero, enseñame a jugar →</button></form><p class="setup-note">v0.1.0 es una prueba local. La conexión entre dispositivos viene después. Una vez cargada, podés jugar sin internet.</p></main>`;}
function mapView(){const t=game.teams[game.turn],legal=expandable(game),n=game.config.size;const fs=fronts(game);return `<section class="map-panel"><div class="panel-heading"><div><div class="eyebrow">EL BARRIO</div><h2>Pintá hasta encontrarte.</h2></div><div class="zoom"><button data-do="zoom-out" aria-label="Alejar mapa">−</button><button data-do="zoom-reset" aria-label="Restablecer zoom">${Math.round(zoom*100)}%</button><button data-do="zoom-in" aria-label="Acercar mapa">+</button></div></div><div class="map-scroll"><div class="board" style="--n:${n};--zoom:${zoom}">${game.board.map((owner,i)=>`<button data-cell="${i}" class="cell ${owner===null?'empty':'owned'} ${legal.includes(i)&&game.actions>0?'available':''} ${selected===i?'selected':''}" style="--club:${owner===null?'#e0d9c5':game.teams[owner].color}" aria-label="Casilla ${i%n+1}, ${Math.floor(i/n)+1}: ${owner===null?'libre'+(legal.includes(i)?', podés expandirte':''):esc(game.teams[owner].name)}" aria-pressed="${selected===i}"><span>${owner===null?(legal.includes(i)&&game.actions>0?'+':'·'):owner+1}</span></button>`).join('')}</div></div><div class="map-legend">${game.teams.map(team=>`<span>${badge(team)} ${esc(team.name)} <b>${territory(game,team.id)}</b></span>`).join('')}</div><div class="selection"><div><b>${selected===null?'Tocá una casilla con +':`Casilla ${selected%n+1}, ${Math.floor(selected/n)+1}`}</b><p>${selected===null?'Elegí primero, confirmá después. Cada casilla cuesta 1 acción.':game.board[selected]===null?(legal.includes(selected)?'Libre y junto a tu bandera. Podés pintarla.':'Libre, pero todavía lejos de tu territorio.'):`Territorio de ${esc(game.teams[game.board[selected]].name)}. Se disputa jugando, no pintando.`}</p></div><button class="primary" data-do="expand" ${selected===null||!legal.includes(selected)||game.actions===0?'disabled':''}>Pintar · 1 acción</button></div><div class="fronts"><div class="eyebrow">FRENTES</div>${fs.length?fs.map(f=>`<div class="front-row">${badge(game.teams[f.rival])}<span>${esc(game.teams[f.rival].name)}</span><b>${f.count}/${game.config.threshold}</b><small>${f.played?'Ya jugaron esta ronda':f.count>=game.config.threshold?'Partido preparado':'Todavía falta frontera'}</small></div>`).join(''):'<p class="muted">Todavía no hay roce. Expandite hacia las otras banderas para armar un partido.</p>'}<p class="fine">${game.config.timing==='end'?'Los partidos preparados se juegan al cerrar el turno.':game.config.timing==='cut'?'Al formarse un frente, se juega y se cierra tu turno.':'Al formarse un frente, se juega y seguís con tus acciones restantes.'} Un partido por pareja en cada ronda.</p></div></section><aside class="sidebar">${clubCard(t)}${lastMatch()}<div class="tip-card"><span>↗</span><p>El objetivo de esta prueba: conquistar barrio, mejorar tu once y sumar puntos en la liga. Sin final obligatorio todavía.</p></div></aside>`;}
function clubCard(t){return `<section class="club-card" style="--club:${t.color}"><div class="eyebrow">TU EQUIPO</div><div class="club-title">${badge(t)}<h3>${esc(t.name)}</h3></div><div class="club-numbers"><div><b>${avg(t)}</b><span>AVG del once</span></div><div><b>${territory(game,t.id)}</b><span>casillas</span></div><div><b>${t.stats.pts}</b><span>puntos</span></div></div><button class="light-button" data-do="squad-tab">Acomodar el once →</button></section>`;}
function matchRow(m){return `<button class="match-row" data-match="${m.id}"><span>${esc(game.teams[m.teams[0]].name)}</span><strong>${m.score.join(' – ')}</strong><span>${esc(game.teams[m.teams[1]].name)}</span><small>Ronda ${m.round} · Ver crónica →</small></button>`;}
function lastMatch(){return `<section class="last-match"><div class="eyebrow">ÚLTIMO SILBATAZO</div>${game.matches.length?matchRow(game.matches[0]):'<div class="empty-match">⚽<p>Por ahora, la pelota<br>está esperando.</p></div>'}</section>`;}
function pCard(p,attrs='',selected=false){return `<button class="player ${selected?'picked':''}" ${attrs}><span class="position">${p.position}</span><span class="player-name">${esc(p.name)}</span><b class="rating ${p.rating>=90?'rare':p.rating>=78?'good':''}">${p.rating}</b></button>`;}
function squadView(){const t=game.teams[game.turn];return `<section class="squad-panel"><div class="panel-heading"><div><div class="eyebrow">EL VESTUARIO</div><h2>Tu once. Tus decisiones.</h2></div><span class="avg-pill">AVG <b>${avg(t)}</b></span></div><p class="muted">Elegí un titular y después un suplente para intercambiarlos. Los cambios son gratis. El AVG es el promedio de los 11 titulares.</p><div class="squad-columns"><div><h3>Titulares <small>11 jugadores</small></h3><div class="pitch"><div class="pitch-circle"></div>${t.squad.map((p,i)=>pCard(p,`data-starter="${i}"`,starter===i)).join('')}</div></div><div><h3>Banco <small>${t.bench.length} jugadores · sin límite</small></h3><p class="fine">${starter===null?'Primero elegí un titular.':`Reemplazar a ${esc(t.squad[starter].name)} (${t.squad[starter].position}).`}</p><div class="bench">${t.bench.map((p,i)=>pCard(p,`data-bench="${i}"`)).join('')}</div></div></div></section>`;}
function marketView(){return `<section class="market-panel"><div class="panel-heading"><div><div class="eyebrow">FICHAJES Y PAQUETES</div><h2>Que entre aire fresco.</h2></div><span class="tag">SIN MONEDAS</span></div><p class="muted">En esta demo, fichar o abrir un paquete cuesta 1 acción. Todos llegan al banco. Los precios y la economía quedan para otra versión.</p><div class="market-grid">${game.market.map((p,i)=>`<article class="transfer-card"><div class="shirt" style="--club:${game.teams[game.turn].color}">${p.rating}</div><span class="eyebrow">${p.position} · ${p.rating>=90?'FIGURA':p.rating>=78?'DESTACADO':'POTRERO'}</span><h3>${esc(p.name)}</h3><button data-sign="${i}" class="primary" ${game.actions<1?'disabled':''}>Fichar · 1 acción</button></article>`).join('')}</div><article class="pack-card"><div><div class="eyebrow">CINCO SORPRESAS</div><h3>Paquete de jugadores</h3><p>5 jugadores al azar. Los mejores son menos comunes.<br>Común 80% · Destacado 18% · Figura 2% por jugador.</p></div><button class="primary" data-do="pack" ${game.actions<1?'disabled':''}>Abrir · 1 acción</button></article></section>`;}
function leagueView(){const scorers={};game.matches.forEach(m=>m.events.forEach(e=>{const key=`${e.team}-${e.playerId}`;scorers[key]??={name:e.player,team:e.team,goals:0};scorers[key].goals++;}));return `<section class="league-panel"><div class="eyebrow">LA LIGA DEL BARRIO</div><h2>Los goles quedan.</h2><p class="muted">Victoria: 3 puntos. Empate: 1 para cada uno. Derrota: 0. El territorio y la liga se muestran por separado.</p><div class="table-scroll"><table><thead><tr><th>Equipo</th>${['PJ','G','E','P','GF','GC','PTS'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${standings(game).map(t=>`<tr><td>${badge(t)} ${esc(t.name)}</td>${['pj','g','e','p','gf','gc','pts'].map(x=>`<td>${t.stats[x]}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="league-bottom"><section><h3>Goleadores</h3>${Object.values(scorers).sort((a,b)=>b.goals-a.goals).slice(0,10).map(p=>`<div class="scorer"><span>${esc(p.name)}<small>${esc(game.teams[p.team].name)}</small></span><b>${p.goals}</b></div>`).join('')||'<p class="muted">El primer gol todavía se hace desear.</p>'}</section><section><h3>Partidos</h3>${game.matches.map(matchRow).join('')||'<p class="muted">La cancha está lista. Falta encontrarse.</p>'}</section></div></section>`;}
function render(){if(!game)return setup();const t=game.teams[game.turn];app.innerHTML=`${header()}<main class="game"><section class="turn-banner" style="--club:${t.color}"><div class="turn-name">${badge(t)}<div><span class="eyebrow">RONDA ${game.round} · ${game.config.mode==='solo'?'RIVALES SIMULADOS':'MISMO DISPOSITIVO'}</span><h1>Turno de ${esc(t.name)}</h1></div></div><div class="actions"><span>${[0,1,2].map(i=>`<i class="${i<game.actions?'full':''}"></i>`).join('')}</span><b>${game.actions}/3 acciones</b><small>El turno lo cerrás vos.</small></div></section><nav class="tabs" aria-label="Secciones">${[['map','↗','Mapa'],['squad','♟','Plantel'],['market','▣','Fichajes'],['league','⚑','Liga']].map(([id,icon,name])=>`<button data-tab="${id}" class="${tab===id?'active':''}" aria-current="${tab===id?'page':'false'}"><span>${icon}</span>${name}</button>`).join('')}</nav><div class="content ${tab==='map'?'map-layout':''}">${tab==='map'?mapView():tab==='squad'?squadView():tab==='market'?marketView():leagueView()}</div><footer class="turn-footer"><span>${game.actions?'Podés pensar todo el tiempo que quieras.':'Sin acciones. Todavía podés cambiar el once.'}</span><button class="primary" data-do="end" ${busy?'disabled':''}>Cerrar turno →</button></footer><p class="footer-note">Guardado automático en este dispositivo · Demo local v${VERSION}</p></main>`;}
function showMatch(m){dialog(`<div class="eyebrow">PARTE DEL POTRERO · RONDA ${m.round}</div><div class="scoreboard"><div>${badge(game.teams[m.teams[0]])}<h3>${esc(game.teams[m.teams[0]].name)}</h3><small>AVG ${m.ratings[0]}</small></div><strong>${m.score.join(' – ')}</strong><div>${badge(game.teams[m.teams[1]])}<h3>${esc(game.teams[m.teams[1]].name)}</h3><small>AVG ${m.ratings[1]}</small></div></div><p class="chronicle">${esc(m.chronicle)}</p><p>${m.winner===null?`${m.tiles.length/2} casillas para cada equipo. Un punto para cada uno.`:`${m.tiles.length} casillas disputadas quedan para ${esc(game.teams[m.winner].name)}. +3 puntos.`}</p><div class="match-events">${m.events.map(e=>`<div><b>${e.minute}′</b>${badge(game.teams[e.team])}<span>Gol de ${esc(e.player)}</span></div>`).join('')||'<p>90 minutos de barro, algún travesaño y ningún gol.</p>'}</div><p class="fine">El resultado y la crónica están guardados. Abrirlos de nuevo no vuelve a sortear el partido.</p><button class="primary" data-do="close">Volver al barrio</button>`);}
function help(){dialog(`<div class="eyebrow">GUÍA DEL POTRERO</div><h2>De cero al primer partido.</h2><ol class="tutorial"><li><b>Ubicá tu bandera.</b><p>Tu equipo tiene un color y un número. Las casillas con + son libres y tocan tu territorio por un lado; las diagonales no cuentan.</p></li><li><b>Elegí cómo gastar tus 3 acciones.</b><p>Pintar una casilla, fichar un jugador o abrir un paquete de cinco cuesta 1 acción. Elegí una casilla y confirmá «Pintar». No hay reloj ni cierre automático por quedarte sin acciones.</p></li><li><b>Acomodá a los titulares.</b><p>En Plantel, tocá un titular y después un suplente. Es gratis. Solo el promedio de tus 11 titulares cuenta en el AVG. Las posiciones te orientan, pero en esta demo no hay penalización por posición.</p></li><li><b>Armá un frente.</b><p>Expandite hacia otro color. Cuando uno de los dos tiene ${game?.config.threshold??3} casillas propias tocando al rival, se prepara un partido. Debe haber al menos 4 casillas de frontera en total. No se juega contra casillas vacías.</p></li><li><b>Jugá la disputa.</b><p>El AVG inclina la balanza, pero hay azar y cualquiera puede ganar. Se disputan 4 o 6 casillas de frontera: el ganador las conquista; con empate se dividen en mitades. La liga suma 3/1/0. Un mismo par juega como máximo una vez por ronda.</p></li><li><b>Cerrá tu turno cuando quieras.</b><p>Por defecto los partidos se juegan al cerrar. Podés probar otras reglas al crear una partida. En modo solo, los rivales juegan simulados; con amigos, pasan el mismo dispositivo.</p></li><li><b>Seguí la liga y la crónica.</b><p>En Liga tenés resultados, goleadores y puntos. La demo es abierta: no impone aún una condición final de victoria ni economía. El progreso se guarda después de cada acción.</p></li></ol><button class="primary" data-do="close">Listo, a jugar</button>`);}
function updates(){dialog(`<div class="eyebrow">NOVEDADES · v${VERSION}</div><h2>Arranca el campeonato.</h2><ul class="updates"><li>Demo local de 2–4 equipos: solo contra simulados o compartiendo pantalla.</li><li>Mapa configurable, expansión adyacente y 3 acciones sin reloj.</li><li>11 titulares, banco ilimitado y cambios gratis.</li><li>Fichajes y paquetes de cinco; sin monedas jugables.</li><li>Partidos con AVG, azar, minutos, goleadores y crónica guardada.</li><li>Disputa territorial, reparto por empate y liga 3/1/0.</li><li>Inicio y momento del partido configurables para probar reglas pendientes.</li><li>Guardado, modo offline después de cargar y aviso de nuevas versiones.</li></ul><button class="primary" data-do="close">Dale</button>`);}
function turnSummary(matches){const recent=game.log.filter(l=>l.round>=game.round-1&&l.team!==game.turn).slice(0,12);dialog(`<div class="eyebrow">${game.config.mode==='solo'?'VOLVIÓ LA PELOTA':'PASÁ EL DISPOSITIVO'}</div><h2>Le toca a ${esc(game.teams[game.turn].name)}.</h2><p>${game.config.mode==='solo'?'Esto hicieron los otros equipos.':'Que el próximo equipo revise el barrio antes de jugar.'}</p><ul class="turn-log">${recent.map(l=>`<li>${badge(game.teams[l.team])}<span>${esc(l.text)}</span></li>`).join('')}</ul>${matches.map(matchRow).join('')}<button class="primary" data-do="close">Entrar a mi turno →</button>`);}
function finish(){if(busy)return;busy=true;const matches=endTurn(game);let guard=0;while(game.teams[game.turn].bot&&guard++<4)matches.push(...botTurn(game));busy=false;selected=null;starter=null;save();render();turnSummary(matches);}
app.addEventListener('submit',e=>{if(e.target.id!=='setup')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const key of ['teams','size','startTiles','threshold'])data[key]=Number(data[key]);game=createGame(data);tab='map';selected=null;starter=null;zoom=1;save();render();help();});
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||button.disabled)return;try{
  const action=button.dataset.do;
  if(action==='close'){modal.close();return;}if(action==='help'){help();return;}if(action==='updates'){updates();return;}
  if(action==='update'){navigator.serviceWorker.getRegistration().then(reg=>{if(reg?.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting.postMessage('activate');}else location.reload();});return;}
  if(action==='new'){dialog('<div class="eyebrow">OTRA PARTIDA</div><h2>¿Arrancamos de nuevo?</h2><p>Esto reemplaza el progreso guardado de la partida actual.</p><div class="modal-actions"><button class="light-button" data-do="close">Seguir jugando</button><button class="primary" data-do="reset">Crear nueva partida</button></div>');return;}
  if(action==='reset'){storage.clear();game=null;modal.close();setup();return;}
  if(button.dataset.match){const m=game.matches.find(m=>m.id===Number(button.dataset.match));if(m)showMatch(m);return;}
  if(!game)return;
  if(button.dataset.tab){tab=button.dataset.tab;render();return;}
  if(action==='squad-tab'){tab='squad';render();return;}
  if(button.dataset.cell!==undefined){selected=Number(button.dataset.cell);render();return;}
  if(action?.startsWith('zoom')){zoom=action==='zoom-reset'?1:Math.max(.8,Math.min(2,zoom+(action==='zoom-in'?.2:-.2)));render();return;}
  if(action==='expand'){const previous=game.turn;const matches=expand(game,selected);const passed=game.turn!==previous;let guard=0;while(game.teams[game.turn].bot&&guard++<4)matches.push(...botTurn(game));selected=null;save();render();if(passed)turnSummary(matches);else if(matches.length)showMatch(matches[0]);else toast('Una casilla más para el barrio.');return;}
  if(button.dataset.starter!==undefined){starter=Number(button.dataset.starter);render();return;}
  if(button.dataset.bench!==undefined){if(starter===null)return toast('Primero elegí el titular que querés cambiar.');swap(game,starter,Number(button.dataset.bench));starter=null;save();render();toast('Cambio hecho. No gastaste acciones.');return;}
  if(button.dataset.sign!==undefined){const p=sign(game,Number(button.dataset.sign));save();render();toast(`${p.name} llegó al banco.`);return;}
  if(action==='pack'){const players=pack(game);save();render();dialog(`<div class="eyebrow">SE ABRIÓ EL PAQUETE</div><h2>Cinco caras nuevas.</h2><div class="pack-reveal">${players.map(p=>pCard(p,'disabled')).join('')}</div><p>Ya están en tu banco. Pasalos al once cuando quieras, sin gastar acciones.</p><button class="primary" data-do="close">Bienvenidos al club</button>`);return;}
  if(action==='end'){if(game.actions>0){dialog(`<div class="eyebrow">CIERRE DE TURNO</div><h2>¿Hasta acá por ahora?</h2><p>Te quedan ${game.actions} acciones. No se acumulan. Los frentes preparados se resolverán y le tocará al siguiente equipo.</p><div class="modal-actions"><button class="light-button" data-do="close">Seguir pensando</button><button class="primary" data-do="confirm-end">Cerrar mi turno</button></div>`);}else finish();return;}
  if(action==='confirm-end'){modal.close();finish();}
}catch(error){busy=false;toast(error.message);}});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
render();
function offerUpdate(){if(document.querySelector('[data-do="update"]'))return;const button=document.createElement('button');button.className='version';button.dataset.do='update';button.textContent='Actualizar ↻';document.querySelector('.header-tools')?.prepend(button);toast('Hay una nueva versión. Podés actualizar cuando quieras.');}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{if(reg.waiting)offerUpdate();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)offerUpdate();});});}).catch(()=>{});}
fetch('./version.json',{cache:'no-store'}).then(r=>r.json()).then(v=>{if(v.version!==VERSION)offerUpdate();}).catch(()=>{});
