import {VERSION,createGame,avg,territory,expandable,fronts,expand,sign,pack,swap,endTurn,botTurn,standings,playerSkills,teamProfile,slotPosition,fitFactor} from './engine.js';
import {storage} from './storage.js';
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
let game=storage.load(),tab='map',selected=null,starter=null,zoom=1,busy=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=t=>`<span class="badge" style="--club:${t.color}">${t.id+1}</span>`;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
function save(){if(!storage.save(game))toast('No se pudo guardar en este navegador. Mantené esta pestaña abierta.');}
function dialog(html,kind=''){modal.className=kind;modal.innerHTML=`<button class="close" data-do="close" aria-label="Cerrar">×</button>${html}`;if(!modal.open)modal.showModal();}
function header(){return `<header><a class="brand" href="./" aria-label="Trucebol inicio">TRUCEBOL<span>FÚTBOL ENTRE TRINCHERAS</span></a><div class="header-tools"><button class="version" data-do="updates">v${VERSION}</button><button class="help" data-do="help" aria-label="Cómo jugar">?</button>${game?'<button class="text-button" data-do="new">Nueva</button>':''}</div></header>`;}
function setup(){app.innerHTML=`${header()}<main class="setup"><section class="intro"><div class="eyebrow">DEMO LOCAL · SIN RELOJ</div><h1>La frontera<br>se juega<br><em>en la cancha.</em></h1><p>Pintá el barrio. Armá tu once.<br>Cuando dos banderas se cruzan,<br>se arregla con una pelota.</p><div class="hero-ball" aria-hidden="true"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="#f7edce" stroke="#234e40" stroke-width="3"/><path d="m50 30 20 14-8 24H38l-8-24Z M10 47l17-8 M28 13l9 18 M73 13l-10 19 M90 47l-18-7 M74 89l-11-20 M26 89l12-21" fill="#234e40" stroke="#234e40" stroke-width="5"/></svg><span>NO HAY APURO.<br>HAY POTRERO.</span></div></section><form id="setup" class="setup-card"><div class="eyebrow">ARMEMOS LA PARTIDA</div><h2>¿Quién se prende?</h2><label>Modo<select name="mode"><option value="solo">Yo contra equipos simulados</option><option value="local">Amigos en el mismo dispositivo</option></select></label><div class="form-row"><label>Equipos<select name="teams"><option value="2">2 equipos</option><option value="3">3 equipos</option><option value="4">4 equipos</option></select></label><label>Mapa<select name="size"><option value="8">8 × 8</option><option value="10">10 × 10</option><option value="12">12 × 12</option></select></label></div><details><summary>Reglas para experimentar</summary><p class="muted">El inicio y el momento del partido siguen a prueba. Estas opciones no fijan la regla final.</p><label>Territorio inicial<select name="startTiles"><option value="3">3 casillas por equipo</option><option value="1">1 casilla por equipo</option><option value="4">4 casillas por equipo</option></select></label><label>Frente necesario<select name="threshold"><option value="3">3 casillas de frontera</option><option value="2">2 casillas de frontera</option><option value="4">4 casillas de frontera</option></select></label><label>Al dispararse un partido<select name="timing"><option value="end">Jugar al cerrar mi turno</option><option value="immediate">Jugar enseguida y seguir mi turno</option><option value="cut">Jugar enseguida y cerrar mi turno</option></select></label></details><button class="primary start" type="submit">Al potrero <span>↗</span></button><p class="fine">3 acciones por turno · Cambios de plantel gratis<br>Guardado automático · Sin monedas en esta demo</p><button type="button" class="text-button" data-do="help">Primero, enseñame a jugar →</button></form><p class="setup-note">v0.2.0 es una prueba local. La conexión entre dispositivos viene después. Una vez cargada, podés jugar sin internet.</p></main>`;}
function mapView(){const t=game.teams[game.turn],legal=expandable(game),n=game.config.size;const fs=fronts(game);return `<section class="map-panel"><div class="panel-heading"><div><div class="eyebrow">EL BARRIO</div><h2>Pintá hasta encontrarte.</h2></div><div class="zoom"><button data-do="zoom-out" aria-label="Alejar mapa">−</button><button data-do="zoom-reset" aria-label="Restablecer zoom">${Math.round(zoom*100)}%</button><button data-do="zoom-in" aria-label="Acercar mapa">+</button></div></div><div class="map-scroll"><div class="board" style="--n:${n};--zoom:${zoom}">${game.board.map((owner,i)=>`<button data-cell="${i}" class="cell ${owner===null?'empty':'owned'} ${legal.includes(i)&&game.actions>0?'available':''} ${selected===i?'selected':''}" style="--club:${owner===null?'#e0d9c5':game.teams[owner].color}" aria-label="Casilla ${i%n+1}, ${Math.floor(i/n)+1}: ${owner===null?'libre'+(legal.includes(i)?', podés expandirte':''):esc(game.teams[owner].name)}" aria-pressed="${selected===i}"><span>${owner===null?(legal.includes(i)&&game.actions>0?'+':'·'):owner+1}</span></button>`).join('')}</div></div><div class="map-legend">${game.teams.map(team=>`<span>${badge(team)} ${esc(team.name)} <b>${territory(game,team.id)}</b></span>`).join('')}</div><div class="selection"><div><b>${selected===null?'Tocá una casilla con +':`Casilla ${selected%n+1}, ${Math.floor(selected/n)+1}`}</b><p>${selected===null?'Elegí primero, confirmá después. Cada casilla cuesta 1 acción.':game.board[selected]===null?(legal.includes(selected)?'Libre y junto a tu bandera. Podés pintarla.':'Libre, pero todavía lejos de tu territorio.'):`Territorio de ${esc(game.teams[game.board[selected]].name)}. Se disputa jugando, no pintando.`}</p></div><button class="primary" data-do="expand" ${selected===null||!legal.includes(selected)||game.actions===0?'disabled':''}>Pintar · 1 acción</button></div><div class="fronts"><div class="eyebrow">FRENTES</div>${fs.length?fs.map(f=>`<div class="front-row">${badge(game.teams[f.rival])}<span>${esc(game.teams[f.rival].name)}</span><b>${f.count}/${game.config.threshold}</b><small>${f.played?'Ya jugaron esta ronda':f.count>=game.config.threshold?'Partido preparado':'Todavía falta frontera'}</small></div>`).join(''):'<p class="muted">Todavía no hay roce. Expandite hacia las otras banderas para armar un partido.</p>'}<p class="fine">${game.config.timing==='end'?'Los partidos preparados se juegan al cerrar el turno.':game.config.timing==='cut'?'Al formarse un frente, se juega y se cierra tu turno.':'Al formarse un frente, se juega y seguís con tus acciones restantes.'} Un partido por pareja en cada ronda.</p></div></section><aside class="sidebar">${clubCard(t)}${lastMatch()}<div class="tip-card"><span>↗</span><p>El objetivo de esta prueba: conquistar barrio, mejorar tu once y sumar puntos en la liga. Sin final obligatorio todavía.</p></div></aside>`;}
function clubCard(t){return `<section class="club-card" style="--club:${t.color}"><div class="eyebrow">TU EQUIPO</div><div class="club-title">${badge(t)}<h3>${esc(t.name)}</h3></div><div class="club-numbers"><div><b>${avg(t)}</b><span>AVG del once</span></div><div><b>${territory(game,t.id)}</b><span>casillas</span></div><div><b>${t.stats.pts}</b><span>puntos</span></div></div><button class="light-button" data-do="squad-tab">Acomodar el once →</button></section>`;}
function matchRow(m){return `<button class="match-row" data-match="${m.id}"><span>${esc(game.teams[m.teams[0]].name)}</span><strong>${m.score.join(' – ')}</strong><span>${esc(game.teams[m.teams[1]].name)}</span><small>Ronda ${m.round} · Ver crónica →</small></button>`;}
function lastMatch(){return `<section class="last-match"><div class="eyebrow">ÚLTIMO SILBATAZO</div>${game.matches.length?matchRow(game.matches[0]):'<div class="empty-match">⚽<p>Por ahora, la pelota<br>está esperando.</p></div>'}</section>`;}
function skillText(p){const s=playerSkills(p);return `<span class="player-skills"><i>ATQ <b>${s.attack}</b></i><i>PAS <b>${s.passing}</b></i><i>DEF <b>${s.defense}</b></i><i>ARQ <b>${s.keeping}</b></i></span>`;}
function pCard(p,attrs='',selected=false,expected=null){const mismatch=expected&&fitFactor(p,expected)<1;return `<button class="player ${selected?'picked':''} ${mismatch?'out-position':''}" ${attrs}><span class="position">${p.position}</span><span class="player-name">${esc(p.name)}${mismatch?`<small>puesto: ${expected}</small>`:''}${skillText(p)}</span><b class="rating ${p.rating>=90?'rare':p.rating>=78?'good':''}">${p.rating}</b></button>`;}
function squadView(){const t=game.teams[game.turn],profile=teamProfile(t);return `<section class="squad-panel"><div class="panel-heading"><div><div class="eyebrow">PLANTEL</div><h2>El once define el partido.</h2></div><span class="avg-pill">AVG <b>${avg(t)}</b></span></div><p class="muted">Los partidos se simulan automáticamente. Pesan los atributos de cada jugador y su encaje en la posición del once. Jugar fuera de puesto reduce su aporte.</p><div class="team-profile"><div><span>ATQ</span><b>${profile.attack}</b></div><div><span>MED</span><b>${profile.midfield}</b></div><div><span>DEF</span><b>${profile.defense}</b></div><div><span>ARQ</span><b>${profile.keeper}</b></div></div><div class="squad-columns"><div><h3>Titulares <small>4-3-3 · 11 jugadores</small></h3><div class="pitch"><div class="pitch-circle"></div>${t.squad.map((p,i)=>pCard(p,`data-starter="${i}"`,starter===i,slotPosition(i))).join('')}</div></div><div><h3>Banco <small>${t.bench.length} jugadores · sin límite</small></h3><p class="fine">${starter===null?'Primero elegí un titular.':`Reemplazar a ${esc(t.squad[starter].name)} · puesto ${slotPosition(starter)}.`}</p><div class="bench">${t.bench.map((p,i)=>pCard(p,`data-bench="${i}"`)).join('')}</div></div></div></section>`;}
function marketView()function marketView(){return `<section class="market-panel"><div class="panel-heading"><div><div class="eyebrow">FICHAJES Y PAQUETES</div><h2>Que entre aire fresco.</h2></div><span class="tag">SIN MONEDAS</span></div><p class="muted">En esta demo, fichar o abrir un paquete cuesta 1 acción. Todos llegan al banco. Los precios y la economía quedan para otra versión.</p><div class="market-grid">${game.market.map((p,i)=>`<article class="transfer-card"><div class="shirt" style="--club:${game.teams[game.turn].color}">${p.rating}</div><span class="eyebrow">${p.position} · ${p.rating>=90?'FIGURA':p.rating>=78?'DESTACADO':'POTRERO'}</span><h3>${esc(p.name)}</h3><button data-sign="${i}" class="primary" ${game.actions<1?'disabled':''}>Fichar · 1 acción</button></article>`).join('')}</div><article class="pack-card"><div><div class="eyebrow">CINCO SORPRESAS</div><h3>Paquete de jugadores</h3><p>5 jugadores al azar. Los mejores son menos comunes.<br>Común 80% · Destacado 18% · Figura 2% por jugador.</p></div><button class="primary" data-do="pack" ${game.actions<1?'disabled':''}>Abrir · 1 acción</button></article></section>`;}
function leagueView(){const scorers={};game.matches.forEach(m=>m.events.filter(e=>!e.type||e.type==='goal').forEach(e=>{const key=`${e.team}-${e.playerId}`;scorers[key]??={name:e.player,team:e.team,goals:0};scorers[key].goals++;}));return `<section class="league-panel"><div class="eyebrow">LA LIGA DEL BARRIO</div><h2>Los goles quedan.</h2><p class="muted">Victoria: 3 puntos. Empate: 1 para cada uno. Derrota: 0. El territorio y la liga se muestran por separado.</p><div class="table-scroll"><table><thead><tr><th>Equipo</th>${['PJ','G','E','P','GF','GC','PTS'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${standings(game).map(t=>`<tr><td>${badge(t)} ${esc(t.name)}</td>${['pj','g','e','p','gf','gc','pts'].map(x=>`<td>${t.stats[x]}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="league-bottom"><section><h3>Goleadores</h3>${Object.values(scorers).sort((a,b)=>b.goals-a.goals).slice(0,10).map(p=>`<div class="scorer"><span>${esc(p.name)}<small>${esc(game.teams[p.team].name)}</small></span><b>${p.goals}</b></div>`).join('')||'<p class="muted">El primer gol todavía se hace desear.</p>'}</section><section><h3>Partidos</h3>${game.matches.map(matchRow).join('')||'<p class="muted">La cancha está lista. Falta encontrarse.</p>'}</section></div></section>`;}
function render(){if(!game)return setup();const t=game.teams[game.turn];app.innerHTML=`${header()}<main class="game"><section class="turn-banner" style="--club:${t.color}"><div class="turn-name">${badge(t)}<div><span class="eyebrow">RONDA ${game.round} · ${game.config.mode==='solo'?'RIVALES SIMULADOS':'MISMO DISPOSITIVO'}</span><h1>Turno de ${esc(t.name)}</h1></div></div><div class="actions"><span>${[0,1,2].map(i=>`<i class="${i<game.actions?'full':''}"></i>`).join('')}</span><b>${game.actions}/3 acciones</b><small>El turno lo cerrás vos.</small></div></section><nav class="tabs" aria-label="Secciones">${[['map','↗','Mapa'],['squad','♟','Plantel'],['market','▣','Fichajes'],['league','⚑','Liga']].map(([id,icon,name])=>`<button data-tab="${id}" class="${tab===id?'active':''}" aria-current="${tab===id?'page':'false'}"><span>${icon}</span>${name}</button>`).join('')}</nav><div class="content ${tab==='map'?'map-layout':''}">${tab==='map'?mapView():tab==='squad'?squadView():tab==='market'?marketView():leagueView()}</div><footer class="turn-footer"><span>${game.actions?'Podés pensar todo el tiempo que quieras.':'Sin acciones. Todavía podés cambiar el once.'}</span><button class="primary" data-do="end" ${busy?'disabled':''}>Cerrar turno →</button></footer><p class="footer-note">Guardado automático en este dispositivo · Demo local v${VERSION}</p></main>`;}
function matchEvent(e){const team=game.teams[e.team],label=e.type==='goal'?(`Gol de ${esc(e.player)}${e.assist?` · asistencia ${esc(e.assist)}`:''}`):e.type==='save'?(`Remate de ${esc(e.player)} · atajado`):e.type==='block'?(`Remate de ${esc(e.player)} · bloqueado por ${esc(e.defender||'la defensa')}`):(`Remate de ${esc(e.player)} · afuera`);return `<div class="match-event ${e.type||'goal'}"><b>${e.minute}′</b>${badge(team)}<span>${label}</span><small>${Number.isFinite(e.xg)?`xG ${e.xg.toFixed(1)}`:''}</small></div>`;}
function statRow(label,a,b,suffix=''){const total=Math.max(1,a+b),left=Math.round(a/total*100);return `<div class="stat-row"><div><b>${a}${suffix}</b><span>${label}</span><b>${b}${suffix}</b></div><div class="stat-track"><i style="width:${left}%"></i></div></div>`;}
function showMatch(m){const a=game.teams[m.teams[0]],b=game.teams[m.teams[1]],stats=m.stats||null,profiles=m.profiles||m.ratings.map(x=>({overall:x})),star=m.star;dialog(`<div class="eyebrow">PARTIDO · RONDA ${m.round}</div><div class="scoreboard match-scoreboard"><div>${badge(a)}<h3>${esc(a.name)}</h3><small>AVG ${m.ratings[0]}</small></div><strong>${m.score.join(' – ')}</strong><div>${badge(b)}<h3>${esc(b.name)}</h3><small>AVG ${m.ratings[1]}</small></div></div><div class="match-profile"><span>Rendimiento previo</span><b>${profiles[0].overall??m.ratings[0]}</b><i>vs</i><b>${profiles[1].overall??m.ratings[1]}</b></div>${stats?`<section class="match-stats"><h3>Estadísticas</h3>${statRow('Posesión',stats[0].possession,stats[1].possession,'%')}${statRow('Remates',stats[0].shots,stats[1].shots)}${statRow('Al arco',stats[0].onTarget,stats[1].onTarget)}${statRow('xG',stats[0].xg,stats[1].xg)}</section>`:''}${star?`<section class="match-star"><span>FIGURA</span><div><b>${esc(star.name)}</b><small>${esc(game.teams[star.team].name)} · ${star.position}</small></div><strong>${star.rating}</strong></section>`:''}<p class="chronicle">${esc(m.chronicle)}</p><p>${m.winner===null?`${m.tiles.length/2} casillas para cada equipo. Un punto para cada uno.`:`${m.tiles.length} casillas disputadas quedan para ${esc(game.teams[m.winner].name)}. +3 puntos.`}</p><section class="match-timeline"><h3>Minuto a minuto</h3>${m.events.map(matchEvent).join('')||'<p class="muted">No hubo remates registrados.</p>'}</section><p class="fine">La simulación se calcula una sola vez a partir del XI y queda guardada. Abrir este informe no vuelve a sortear el partido.</p><button class="primary" data-do="close">Volver</button>`,'match-modal');}
function help(){dialog(`<div class="eyebrow">GUÍA</div><h2>De cero al primer partido.</h2><ol class="tutorial"><li><b>Expandí tu territorio.</b><p>Las casillas con + son libres y tocan tu territorio por un lado. Pintar cuesta 1 acción.</p></li><li><b>Usá tus 3 acciones.</b><p>Podés expandir, fichar o abrir paquetes. No hay reloj y el turno lo cerrás vos.</p></li><li><b>Armá el once.</b><p>Los cambios entre titulares y banco son gratis. Cada jugador tiene ATQ, PAS, DEF y ARQ. El puesto natural y el puesto que ocupa en el 4-3-3 afectan su rendimiento.</p></li><li><b>Generá un frente.</b><p>Cuando la frontera con otro equipo llega al umbral, se prepara un partido. El momento exacto del partido sigue siendo una regla experimental configurable.</p></li><li><b>El partido es automático.</b><p>No hay controles dentro del partido. El motor usa los atributos y las posiciones del XI para simular posesión, generación de remates, definición, defensa y atajadas. El azar existe, pero un mejor equipo tiene mejores probabilidades.</p></li><li><b>Revisá el informe.</b><p>Cada partido guarda marcador, posesión, remates, tiros al arco, xG, atajadas, goles, asistencias, figura y minuto a minuto. El resultado nunca se recalcula al abrirlo de nuevo.</p></li><li><b>Territorio y liga.</b><p>El ganador toma la zona disputada; con empate se divide en mitades. La liga suma 3/1/0. La condición final de victoria todavía no está fijada.</p></li></ol><button class="primary" data-do="close">Cerrar guía</button>`);}
function updates(){dialog(`<div class="eyebrow">NOVEDADES · v${VERSION}</div><h2>Plan Cóndor: partidos.</h2><ul class="updates"><li>Partidos completamente simulados: no hay minijuegos ni decisiones durante los 90 minutos.</li><li>Cada jugador ahora tiene ATQ, PAS, DEF y ARQ además de su valoración general.</li><li>La posición natural importa: jugar fuera de puesto reduce el aporte al equipo.</li><li>El motor separa ataque, mediocampo, defensa y arquero para construir cada partido.</li><li>Nuevo informe con posesión, remates, tiros al arco, xG, atajadas, asistencias, figura y minuto a minuto.</li><li>Los resultados siguen siendo persistentes y deterministas al recargar.</li><li>Las partidas de v0.1 se migran sin borrar el progreso.</li><li>Las reglas pendientes sobre territorio inicial y momento del partido siguen configurables.</li></ul><button class="primary" data-do="close">Cerrar</button>`);}
function turnSummary(matches){const recent=game.log.filter(l=>l.round>=game.round-1&&l.team!==game.turn).slice(0,12);dialog(`<div class="eyebrow">${game.config.mode==='solo'?'VOLVIÓ LA PELOTA':'PASÁ EL DISPOSITIVO'}</div><h2>Le toca a ${esc(game.teams[game.turn].name)}.</h2><p>${game.config.mode==='solo'?'Esto hicieron los otros equipos.':'Que el próximo equipo revise el barrio antes de jugar.'}</p><ul class="turn-log">${recent.map(l=>`<li>${badge(game.teams[l.team])}<span>${esc(l.text)}</span></li>`).join('')}</ul>${matches.map(matchRow).join('')}<button class="primary" data-do="close">Entrar a mi turno →</button>`);}
function finish(){if(busy)return;busy=true;const matches=endTurn(game);let guard=0;while(game.teams[game.turn].bot&&guard++<4)matches.push(...botTurn(game));busy=false;selected=null;starter=null;save();render();turnSummary(matches);}
app.addEventListener('submit',e=>{if(e.target.id!=='setup')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const key of ['teams','size','startTiles','threshold'])data[key]=Number(data[key]);game=createGame(data);tab='map';selected=null;starter=null;zoom=1;save();render();help();});
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||button.disabled)return;try{
  const action=button.dataset.do;
  if(action==='close'){modal.close();return;}if(action==='help'){help();return;}if(action==='updates'){updates();return;}
  if(action==='update'){navigator.serviceWorker.getRegistration().then(reg=>{if(reg?.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting.postMessage('activate');}else location.reload();});return;}
  if(action==='new'){dialog('<div class="eyebrow">OTRA PARTIDA</div><h2>¿Arrancamos de nuevo?</h2><p>Esto reemplaza el progreso guardado de la partida actual.</p><div class="modal-actions"><button class="light-button" data-do="close">Seguir jugando</button><button class="primary" data-do="reset">Crear nueva partida</button></div>');return;}
  if(action==='reset'){storage.clear();game=null;modal.close();setup();return;}
  if(button.dataset.match){const m=game.matches.find(m=>m.id===Number(button.dataset.match));if(m)showMatch(m);return;}
  if(!game)return;
  if(button.dataset.tab){tab=button.dataset.tab;render();return;}
  if(action==='squad-tab'){tab='squad';render();return;}
  if(button.dataset.cell!==undefined){selected=Number(button.dataset.cell);render();return;}
  if(action?.startsWith('zoom')){zoom=action==='zoom-reset'?1:Math.max(.8,Math.min(2,zoom+(action==='zoom-in'?.2:-.2)));render();return;}
  if(action==='expand'){const previous=game.turn;const matches=expand(game,selected);const passed=game.turn!==previous;let guard=0;while(game.teams[game.turn].bot&&guard++<4)matches.push(...botTurn(game));selected=null;save();render();if(passed)turnSummary(matches);else if(matches.length)showMatch(matches[0]);else toast('Una casilla más para el barrio.');return;}
  if(button.dataset.starter!==undefined){starter=Number(button.dataset.starter);render();return;}
  if(button.dataset.bench!==undefined){if(starter===null)return toast('Primero elegí el titular que querés cambiar.');swap(game,starter,Number(button.dataset.bench));starter=null;save();render();toast('Cambio hecho. No gastaste acciones.');return;}
  if(button.dataset.sign!==undefined){const p=sign(game,Number(button.dataset.sign));save();render();toast(`${p.name} llegó al banco.`);return;}
  if(action==='pack'){const players=pack(game);save();render();dialog(`<div class="eyebrow">SE ABRIÓ EL PAQUETE</div><h2>Cinco caras nuevas.</h2><div class="pack-reveal">${players.map(p=>pCard(p,'disabled')).join('')}</div><p>Ya están en tu banco. Pasalos al once cuando quieras, sin gastar acciones.</p><button class="primary" data-do="close">Bienvenidos al club</button>`);return;}
  if(action==='end'){if(game.actions>0){dialog(`<div class="eyebrow">CIERRE DE TURNO</div><h2>¿Hasta acá por ahora?</h2><p>Te quedan ${game.actions} acciones. No se acumulan. Los frentes preparados se resolverán y le tocará al siguiente equipo.</p><div class="modal-actions"><button class="light-button" data-do="close">Seguir pensando</button><button class="primary" data-do="confirm-end">Cerrar mi turno</button></div>`);}else finish();return;}
  if(action==='confirm-end'){modal.close();finish();}
}catch(error){busy=false;toast(error.message);}});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
render();
function offerUpdate(){if(document.querySelector('[data-do="update"]'))return;const button=document.createElement('button');button.className='version';button.dataset.do='update';button.textContent='Actualizar ↻';document.querySelector('.header-tools')?.prepend(button);toast('Hay una nueva versión. Podés actualizar cuando quieras.');}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{if(reg.waiting)offerUpdate();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)offerUpdate();});});}).catch(()=>{});}
fetch('./version.json',{cache:'no-store'}).then(r=>r.json()).then(v=>{if(v.version!==VERSION)offerUpdate();}).catch(()=>{});
